---
id: Date_Parser
name: Date_Parser
full: Date parser library
description: |
  A library for natural-language date parsing, with support for multiple languages and locales.
list: dev
type: library
homepage: https://www.horde.org/libraries/Horde_Date_Parser
authors:
  -
    name: Jan Schneider
    user: jan
    email: jan@horde.org
    active: true
    role: lead
  -
    name: Chuck Hagenbuch
    user: chuck
    email: chuck@horde.org
    active: false
    role: lead
version:
  release: 3.0.0alpha4
  api: 3.0.0alpha1
state:
  release: alpha
  api: alpha
license:
  identifier: LGPL-2.1-only
  uri: http://www.horde.org/licenses/lgpl21
dependencies:
  required:
    php: ^7.4 || ^8
    composer:
      horde/date: ^3
      horde/support: ^3
      horde/util: ^3
  optional:
    composer:
      horde/test: ^3
